menu:
  Home: /
  About: /about
  Archives: /archives

widgets:
- search
- tag
- twitter

excerpt_link: Read More

twitter:
  username: masterzheng
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: true
  google: false
  pinterest: false
  weibo: true

fancybox: true

google_analytics:
rss:
